### ISSUE TITLE
Order of casting when dynamically instantiate object

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#1]
The problem right now is that the transpiler is placing the new statement in the wrong place:

```return new (<MovieManager>Start.pRootClass() )```

So for now we are implmenting the fix manually:

```return (<MovieManager>(new Start.pRootClass()) )```

In the future, the transpiler should not suffer from this problem.

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#67
