### ISSUE TITLE
static constants on superclasses are handled as Classnames instead

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#12]
in superclass:
```
        protected static const UP:int = 0;
```
in extending class:
```
            pBlends = new Vector.<Number>(3);
            pBlends[UP] = 85;
```
resulting TS for extending class:
```
    import { UP } from "./UP";
            this.pBlends = [];
            this.pBlends[UP] = 85;
```

so it i does not understand that this is a static const on the superclass, but instead handles it as a Class-name, creating a import statement for it.

AS3 FIX: make sure the Transpiler understand it is a static const.

instead of this:
```            pBlends = new Vector.<Number>(3);
            pBlends[UP] = 85;
```
this
```
            pBlends = new Vector.<Number>(3);
            pBlends[Button.UP] = 85;
```

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#56
