### ISSUE TITLE
difference between ts and as3 in scope for vars

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#15]
This works ok in as3:
```
if (true) { 
    var test:Number = 2;
}
test += 1;
```
but it will not compile in ts, because of test not being defined.
AS3FIX:
move ithe var declaration, so that it works for ts
example before:
```
if (true) { 
    var test:Number = 2;
}
test += 1;
```
after:
```
var test:Number = 0;
if (true) { 
    test=2;
}
test += 1;
```

**Comment by djtuBIG-MaliceX** [comment]
No idea where you're getting that undefined idea. That would be true for the 'let' keyword (introduced in ES6 which TypeScript implements), but for var it's perfectly legal as it is global-scope (by default), consistent with JavaScript.

The error being experienced here according to my tslint is **"Operator '+' cannot be applied to types 'Number' and '1'."**  

The AS3Fix code example in your post also does not work (eg: same error in bold)

**Comment by 80prozent** [comment]
just retested, and my FlashDevelop compiles above as3-snippet with no error.

obviously just talking about compiler-errors here.

i think i had the issue in TS both with `let` and `var`. might be that it only was with `let` tho...

another example of the issue:

```
for (let something:any of someArray){
    // do something here
}
for (something of someArray){
    // do something here
}
```
ts gives me errors when compiling this.

this compiles fine:
```
let something:any;
for (something of someArray){
    // do something here
}
for (something of someArray){
    // do something here
}
```

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#53
