### ISSUE TITLE
can not support identifier including namespaces

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#17]
the transpiler will mess up if we use as3 classnames including namespaces.

`var sprite:flash.display.Sprite=new flash.display.Sprite()`

will work in as3, but not in ts.

in most cases this is no issue, and the namespace can just be removed, but sometimes we need the namespace to difference between classes with same name in different package

for example:

```
var sprite1:flash.display.Sprite=new flash.display.Sprite();
var sprite2:starling.display.Sprite=new starling.display.Sprite();
```

**Comment by ajsantander** [comment]
This could be something we ask sunflower not to do.

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#51
