### ISSUE TITLE
replacment for as3 `is` to check if string is a classname

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#2]
is there any reliable ts-solution to check if a class exists in the scope for a given name (string) and provides a constructer ?

**Comment by djtuBIG-MaliceX** [comment]
Not sure why you would do that. According to the Adobe AS3 docs, the 'is' operator is mainly to check for whether an object is indeed a given Class.

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/operators.html#is

A semi-relevant stackoverflow topic on its equivalent use (in the converse case): http://stackoverflow.com/questions/4582761/as3-is-not-keyword

Also, a quick example in TypeScript for equivalent behaviour _as described in the AS3 docs example_:

```
class Foo {
  constructor() {
    console.log("Foo() created");
  }
}

var bar = new Foo();

// note the comparison compares the Class name, not a string of the class name.
if (bar.constructor == Foo) {
  alert("yay!");
} else { // the bottom part should not occurobject instance.
  alert("didn't work out now, did it?");
}
```

**Comment by 80prozent** [comment]
think i was not very clear with the description.

So my input is a string, and it might be a class-name, but could also be a name of a asset that is already loaded and instanced

this is what seem to work ok for now:

```

		var tDisplayObj:DisplayObject;
		try{

			tDisplayObj = new tName();
		}
		catch(e) {
// input sting is not a class that can be constructed
}
```

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#66
