### ISSUE TITLE
Array sorting

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#3]
```
var tSort:Array = tTrans.sort(Array.RETURNINDEXEDARRAY); 
```
does not work in TS

**Comment by djtuBIG-MaliceX** [comment]
Array.prototype.sort() in standard JavaScript (which TypeScript also implements) is not the same as with AS3.

Reference:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

Example:

```
let results = [9,2,5,1,5,7];
results.sort((a,b) => {return (a<b) ? -1 : (a>b) ? 1 : 0; });
console.log(results); // prints [1, 2, 5, 5, 7, 9]
```

**Comment by 80prozent** [comment]
yep. 

well some as3 sorts can be transpiled into valid ts:
as3:
```
		tArray.sort(function(tA:*, tB:*):int {
				if (tA[tProp] < tB[tProp]) return -1;
				if (tA[tProp] > tB[tProp]) return 1;
				return 0;
			})
```
ts:
```
		tArray.sort(function (tA:any, tB:any):number {
			if (tA[tProp] < tB[tProp]) return -1;
			if (tA[tProp] > tB[tProp]) return 1;
			return 0;
		})
```

but ye. others usage of array.sort must be fixed manually.

for example, i think the as3 code that i posted when creating this issue must be replaced with using `map` instead of `sort`

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#65
