### ISSUE TITLE
upcasts needed in TS

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#7]
in as3 this works:
```
var tChild:DisplayObject = tDO.getChildAt(i)
        if (tChild is ICutoutableNode) {
            var tCutoutNode:ICutoutableNode = tChild as ICutoutableNode
            tCutoutNode.fFind3DElementsToCutOut()
```
the converted TS does not:
```
var tChild:DisplayObject = tDO.getChildAt(i)
            if (tChild instanceof ICutoutableNode) {
                var tCutoutNode:ICutoutableNode = (<ICutoutableNode>tChild )
```
a possible solution would be to cast to anybefore casting to ICutoutableNode:
```
var tChild:DisplayObject = tDO.getChildAt(i)
            if (tChild instanceof ICutoutableNode) {
                var tCutoutNode:ICutoutableNode = (<ICutoutableNode><any>tChild )
```
but i think its kind of nasty, and also i do not see a way to apply a fix in as3, so would be happy for other suggestions

**Comment by 80prozent** [comment]
rob commented:
upcasting only works if the class being upcast exists somewhere down the inheritance tree of the upcasting class. With an interface, this is obviously not the case so one solution would be to upcast to the class that implements ICutoutableNode.

**Comment by 80prozent** [comment]
i am not sure we can just cast to the class that implements ICutoutableNode.

There could be multiple classes that fits that requirements, and the code might be build to handle multiple of those classes. so if we would choose one of the classes that implements ICutoutableNode, it might break if our castee is not of these specific type.

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#61
