### ISSUE TITLE
Unreachable code in TS

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#9]
typescript wont compile with unreachable code like unreachable `break` or `return`.

on the other side some as3-compilers (FlashDevelop) need those unreachable returns in order to compile.

Error in FlashDevelop if we remove unreachable returns from functions:
```
Error: Function does not return a value.
```

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#59
